### ISSUE TITLE
Is there a way to bind to existing iframes?

### ISSUE THREAD

**Issue by miguelperez** [franleplant/ibridge#13]
Currently it seems like the only way is for the parent to include the child iframe, my need to is bind to 1 or more iframes that are already added in the DOM.

**Comment by franleplant** [comment]
Hi Miguel! There’s a wip PR with upcoming changes that will enable this
among other things, Ill try to make it happen this week. The merge with
post-me was cancelled for now but there was a lot to be learned from that
discussion and that is what is happening in the mentioned PR

**Comment by miguelperez** [comment]
Thanks, I will wait for the changes to be up.
In the meantime I think I will try to make it work with ibridge creating the iframe, so I can set the communication part between the two, and after your PRs are merged then I will update and make the changes so to use an existing iframe.
