### ISSUE TITLE
emitToParent (maybe others) requires two args when second should be optional

### ISSUE THREAD

**Issue by cmawhorter** [franleplant/ibridge#5]
thanks for putting this together.  it does a good job of addressing some of my nagging problems with postmate.  

this currently has a ts error: `emitToParent('some_event')` and expects a second data: unknown argument.  i believe it should be `data?: unknown`.  my workaround is to do `emitToParent('some_event', undefined)`

**Comment by franleplant** [comment]
yeah, I can make `data` optional for sure
